# Generated by Django 5.2.5 on 2025-11-05 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Department of Computer Science', max_length=255, unique=True)),
                ('school', models.CharField(blank=True, help_text='e.g., School of Engineering and Technology', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the department.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(help_text="A key topic, e.g., 'Hostel Information', 'Admissions Process', 'Library'", max_length=255, unique=True)),
                ('content', models.TextField(help_text='The detailed answer for this topic.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords to help the AI find this topic.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(help_text='e.g., Professor, Head of Department', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Master of Computer Applications', max_length=255)),
                ('code', models.CharField(blank=True, help_text='e.g., MCA', max_length=50, null=True)),
                ('eligibility', models.TextField(blank=True, help_text='Detailed eligibility criteria.', null=True)),
                ('fee_structure', models.TextField(blank=True, help_text='Detailed fee structure. You can use text or simple JSON.', null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g., 2 Years (4 Semesters)', max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
    ]
