# Generated by Django 5.2.5 on 2025-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_department_generalinfo_faculty_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.DeleteModel(
            name='GeneralInfo',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
